# Generated by Django 5.2.9 on 2025-12-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VisitRecord",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uid", models.IntegerField(verbose_name="用户id")),
                ("blog_id", models.IntegerField(db_index=True, verbose_name="博客id")),
                (
                    "visit_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="访问时间"),
                ),
            ],
            options={
                "verbose_name": "访问记录",
                "verbose_name_plural": "访问记录",
            },
        ),
    ]
