# Generated by Django 5.2.9 on 2025-12-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xblogs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadRecord",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uid", models.IntegerField(verbose_name="用户id")),
                ("blog_id", models.IntegerField(db_index=True, verbose_name="博客id")),
                (
                    "read_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="访问时间"),
                ),
            ],
            options={
                "verbose_name": "阅读记录",
                "verbose_name_plural": "阅读记录",
            },
        ),
        migrations.DeleteModel(
            name="VisitRecord",
        ),
    ]
