# Generated by Django 5.2.9 on 2025-12-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xblogs", "0002_readrecord_delete_visitrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="readrecord",
            name="unlogined",
            field=models.BooleanField(default=False, verbose_name="是否未登录"),
        ),
    ]
